### ISSUE TITLE
error when tryig to run program

### ISSUE THREAD

**Issue by nachovoss** [bigvisionai/pyOpenAnnotate#6]
when running:  annotate --img  "images_dir_path"

I  get the following error

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\Scripts\annotate.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\annotation\annotate.py", line 320, in main
    bboxes = get_init_bboxes(thresh)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\annotation\annotate.py", line 92, in get_init_bboxes
    contours, _ = cv2.findContours(img, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)

**Comment by kXborg** [comment]
Hi @nachovoss,

Which version of OpenCV are you using? It is a known issue with `findContours`. [StackOverflow](https://stackoverflow.com/questions/25504964/opencv-python-cv2-findcontours-valueerror-too-many-values-to-unpack).
