### ISSUE TITLE
Traceback in showlbls (visualize.py)

### ISSUE THREAD

**Issue by m6z** [bigvisionai/pyOpenAnnotate#8]
Amazing project - thanks for creating!  Ran into one problem:

```
+ python visualize.py --img input1 --ann labels --thickness 10
Traceback (most recent call last):
  File "/home/mike/py/pyOpenAnnotate/src/tools/visualize.py", line 162, in <module>
    main()
  File "/home/mike/py/pyOpenAnnotate/src/tools/visualize.py", line 126, in main
    annotated_img = draw_annotations(img, bounding_boxes, thickness)
  File "/home/mike/py/pyOpenAnnotate/src/tools/visualize.py", line 63, in draw_annotations
    cv2.rectangle(img, p1, p2, (0,255,0), thickness)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2
```

Changing function draw_annotations in visualize.py to the following appears to resolve the issue:

```
def draw_annotations(img, bboxes, thickness=2):
    for bbox in bboxes:
        p1 = bbox[0]
        p2 = bbox[1]
        cv2.rectangle(img, p1, p2, (0,255,0), thickness)
    return img
```

**Comment by kXborg** [comment]
Hi @m6z, 

I can reproduce the error. Would you like to create a pull request?
